spring:
  datasource:
    # url: jdbc:h2:file:./database/dev/backup_data;MODE=MySQL
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest

# Set my Kafka Topics
mykafka:
  topics:
    topic-name: fad

logging.file:
  path: ./home/user
  name: my.log

server.port: 8090

