spring:
  datasource:
    url: jdbc:postgresql://order-event-driven-quarkus-postgres-1:5432/db_order-app
    username: guilherme_user
    password: 0biy0]Q99y2?
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest

# Set my Kafka Topics
mykafka:
  topics:
    order:
      insert: INSERT_ODER_MANY
      update: UPDATE_ODER_MANY
  timeout:
    waiting:
      response: 480

  path: ./home/user
  name: my.log

server.port: 8081

